
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 03 22:30:28 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 40;
  public static final int CONST = 16;
  public static final int SEMI = 17;
  public static final int CONTINUE = 12;
  public static final int LROUND = 2;
  public static final int MINUS = 22;
  public static final int RROUND = 3;
  public static final int AND = 30;
  public static final int RBOX = 5;
  public static final int LT = 33;
  public static final int OR = 29;
  public static final int BOOL = 39;
  public static final int QMARK = 20;
  public static final int COMMA = 19;
  public static final int INC = 27;
  public static final int DIV = 25;
  public static final int GEQ = 36;
  public static final int PLUS = 23;
  public static final int IF = 41;
  public static final int ASSIGN = 21;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int LCURLY = 6;
  public static final int NUMBER = 37;
  public static final int MOD = 26;
  public static final int NEQ = 32;
  public static final int IDENT = 38;
  public static final int BREAK = 11;
  public static final int VOID = 15;
  public static final int EQ = 31;
  public static final int RCURLY = 7;
  public static final int COLON = 18;
  public static final int ELSE = 42;
  public static final int READ = 9;
  public static final int WHILE = 44;
  public static final int PROG = 8;
  public static final int LEQ = 34;
  public static final int LBOX = 4;
  public static final int DEC = 28;
  public static final int GT = 35;
  public static final int DO = 43;
  public static final int PRINT = 10;
}

